### ISSUE TITLE
upsert

### ISSUE THREAD

**Issue by kostja** [funny-falcon/tarantool16-ruby#1]
Support upsert  tarantool/tarantool#905

**Comment by funny-falcon** [comment]
upsert isn't documented yet in [IProto Protocol](http://tarantool.org/doc/dev_guide/box-protocol.html)

**Comment by funny-falcon** [comment]
neither it is tested in net.box.test.lua or sql.test.lua

**Comment by kostja** [comment]
The project has moved to tarantool/ org
